import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Navbar from "~/components/Navbar";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="flex h-screen flex-col overflow-auto bg-white">
        <Navbar />
        <div className="flex h-full w-full   items-center justify-between px-10">
          <div className="flex w-full max-w-[550px] flex-col">
            <div>
              <h1 className="text-4xl font-bold">{"Hi, I'm Lance Mvungama"}</h1>
              <h3 className="mt-1 text-2xl font-bold">Full-stack Developer</h3>
              <p className="mt-4 w-full max-w-[420px] text-sm">
                Based in Gauteng South Africa with 2 years of expirience in the
                field using modern technology and frameworks.
              </p>
            </div>
            <button className="relative z-20 mt-4 w-40 rounded-md border border-black px-6 py-2 text-sm  tracking-[1px] text-black ease-in-out before:absolute before:left-0 before:top-0 before:-z-10 before:h-full before:w-0 before:rounded-md before:bg-red-500 before:transition-all before:duration-[.5s] hover:before:w-full">
              Resume
            </button>
          </div>
        </div>
      </section>
    </>
  );
};

export default Home;
